// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1pb9uWv3TI1Z3pYNpfmlPfsKS2-0eTHs',
    appId: '1:431998949177:web:fdc1633bf17ebc80683ae8',
    messagingSenderId: '431998949177',
    projectId: 'drivora-app-f9e6c',
    authDomain: 'drivora-app-f9e6c.firebaseapp.com',
    storageBucket: 'drivora-app-f9e6c.firebasestorage.app',
    measurementId: 'G-4RG4TVP5XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjqaLQt-85rbyf8zbel27PsNlN4xw-ibI',
    appId: '1:431998949177:android:29e08dec3eec7a99683ae8',
    messagingSenderId: '431998949177',
    projectId: 'drivora-app-f9e6c',
    storageBucket: 'drivora-app-f9e6c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-wdu9fx8GpDg9TeV8U7DjeVOXna0NcQ',
    appId: '1:431998949177:ios:ff0a766398fc342c683ae8',
    messagingSenderId: '431998949177',
    projectId: 'drivora-app-f9e6c',
    storageBucket: 'drivora-app-f9e6c.firebasestorage.app',
    iosBundleId: 'com.example.drivoraFlutter',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh-wdu9fx8GpDg9TeV8U7DjeVOXna0NcQ',
    appId: '1:431998949177:ios:ff0a766398fc342c683ae8',
    messagingSenderId: '431998949177',
    projectId: 'drivora-app-f9e6c',
    storageBucket: 'drivora-app-f9e6c.firebasestorage.app',
    iosBundleId: 'com.example.drivoraFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1pb9uWv3TI1Z3pYNpfmlPfsKS2-0eTHs',
    appId: '1:431998949177:web:393ce333bb9fb5cd683ae8',
    messagingSenderId: '431998949177',
    projectId: 'drivora-app-f9e6c',
    authDomain: 'drivora-app-f9e6c.firebaseapp.com',
    storageBucket: 'drivora-app-f9e6c.firebasestorage.app',
    measurementId: 'G-KLM7QJRP2G',
  );
}
